name: Build

on:
  push:
    tags-ignore:
      - "**"
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  call-ghlint:
    name: Call Lint Github workflows
    uses: azazeal/workflows/.github/workflows/ghlint.yml@master
    permissions:
      pull-requests: write

  docker:
    name: Build & push Docker image
    runs-on: ubuntu-latest

    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Extract image metadata
        id: metadata
        uses: docker/metadata-action@v5
        with:
          images: |
            azazeal/vasctest
          tags: |
            type=sha,prefix=,format=short

      - name: Build & publish
        uses: docker/build-push-action@v5
        with:
          push: ${{ github.ref == 'refs/heads/master' }}
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
